apiVersion: v1
kind: Secret
metadata:
  name: cryptobuyer-secret
  labels:
    app: cryptobuyer
  namespace: cryptobuyer-admin
type: Opaque
data:
  password: LW1EOGV3aVFOQ3F2WGh3QzVOZ0E4UDFZZFdSOWRqX00K